In [17]:
import pandas as pd
import streamlit as st
import mysql.connector
from mysql.connector import connection
from sqlalchemy import create_engine

In [18]:
mydb = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "swapna2021",
    database = "ecomm"
)

productSkuDf

In [52]:
cursor = mydb.cursor()

queryproductSkuDf = "SELECT * FROM ecomm.product_sku"

cursor.execute("SELECT * FROM ecomm.product_sku")

sku = cursor.fetchall()
 
productSkuDf = pd.read_sql(queryproductSkuDf, mydb)

productSkuDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\1393311070.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  productSkuDf = pd.read_sql(queryproductSkuDf, mydb)

,product_sku_id,avg_customer_rating,image_url,price,product_id,product_sku_cd,rating_count,trending_product_flg,bar_code,count,discount,list_price,sku_description,status
0,346,None,toor_dal_1.jpg,100.0,343,TOORDAL1,None,Y,0,0,0,100,1/2 Kg,Available
1,349,None,toor_dal_1.jpg,180.0,343,TOORDAL2,None,None,0,0,0,180,1 Kg,Available
2,364,None,green_gram_001.jpg,10.0,361,MOONGDAL2,None,Y,0,0,0,100,1/2 Kg,Available
3,367,None,green_gram_001.jpg,180.0,361,MOONGDAL,None,None,0,0,0,180,1 Kg,Available
4,374,None,desi_ghee1.jpg,300.0,370,GHEE001,None,Y,44144,0,0,300,1/2 Kg,Available
5,380,None,desi_ghee1.jpg,600.0,370,GHEE001,None,None,44144,0,0,600,1 Kg,Available
6,400,None,chana_dal.jpg,80.0,398,CHANNADAL,None,Y,0,0,0,80,1 Kg,Available
7,403,None,chana_dal.jpg,40.0,398,CHANNADAL01,None,None,0,0,0,40,1/2 Kg,Available
8,409,None,carrots1.jpg,50.0,406,CARROTS,None,Y,0,0,0,50,1/2 Kg,Available
9,412,None,carrots1.jpg,100.0,406,CARROTS,None,None,0,0,0,100,1 Kg,Available
10,418,None,potatoes1.jpg,30.0,415,POTATOES,None,Y,0,0,0,30,1 Kg,Available
11,421,None,potatoes1.jpg,15.0,415,POTATOES,None,None,0,0,0,15,1/5 Kg,Available
12,427,None,caulifower1.jpg,20.0,424,CAULIFLOWER,None,Y,0,0,0,20,1/2 Kg,Available
13,430,None,caulifower1.jpg,40.0,424,CAULIFLOWER,None,None,0,0,0,40,1 Kg,Available
14,436,None,tomatoes1.jpg,50.0,433,TOMATOES,None,Y,0,0,0,50,1 Kg,Available
15,439,None,tomatoes1.jpg,25.0,433,TOMATOES,None,None,0,0,0,25,1/2 Kg,Available
16,445,None,green_beans_1.jpg,40.0,442,GREENBEANS,None,Y,0,0,0,40,1/2 Kg,Available
17,448,None,green_beans_1.jpg,80.0,442,GREENBEANS,None,None,0,0,0,80,1 Kg,Available
18,454,None,mango_pickle_1.jpg,150.0,451,MANGOPICKLE,None,y,0,0,0,150,1 Kg,Available
19,457,None,mango_pickle_1.jpg,75.0,451,MANGOPICKLE,None,None,0,0,0,75,1/5 Kg,Available
20,463,None,lime_pickle_1.jpg,75.0,460,LIMEPICKLE,None,y,0,0,0,75,1/5 Kg,Available
21,466,None,lime_pickle_1.jpg,150.0,460,LIMEPICKLE,None,None,0,0,0,150,1 Kg,Available
22,472,None,mixed_vegetable_pickle.jpg,140.0,469,MIXEDVEGPICKLE,None,y,0,0,0,140,1 Kg,Available
23,475,None,mixed_vegetable_pickle.jpg,70.0,469,MIXEDVEGPICKLE,None,None,0,0,0,70,1/2 Kg,Available
24,481,None,ginger_pickle.jpg,70.0,478,GINGERPICKLE,None,None,0,0,0,70,1/2 Kg,Available
25,484,None,ginger_pickle.jpg,140.0,478,GINGERPICKLE,None,None,0,0,0,140,1 Kg,Available
26,490,None,mixture.jpg,30.0,487,MIXTURE,None,y,0,0,0,30,150 gms,Available
27,493,None,mixture.jpg,50.0,487,MIXTURE,None,None,0,0,0,50,300 gms,Available
28,499,None,sweets.jpg,300.0,496,SWEETS,None,None,0,0,0,300,1 Kg,Available
29,502,None,sweets.jpg,150.0,496,SWEETS,None,None,0,0,0,150,1/2 Kg,Available
30,508,None,mango.jpg,100.0,505,MANGO,None,y,0,0,0,100,1/2 Kg,Available
31,511,None,mango.jpg,200.0,505,MANGO,None,None,0,0,0,200,1 Kg,Available
32,517,None,papaya.jpg,100.0,514,PAPAYA,None,y,0,0,0,100,1 Kg,Available
33,520,None,papaya.jpg,50.0,514,PAPAYA,None,None,0,0,0,50,1/2 Kg,Available
34,526,None,sapota.jpg,80.0,523,SAPOTA,None,None,0,0,0,80,1/2 Kg,Available
35,529,None,sapota.jpg,160.0,523,SAPOTA,None,None,0,0,0,160,1 Kg,Available
36,535,None,cheddar_cheese.jpg,300.0,532,CHEDDARCHEESE,None,None,0,0,0,300,1 Kg,Available
37,538,None,cheddar_cheese.jpg,150.0,532,CHEDDARCHEESE,None,None,0,0,0,150,1/2 Kg,Available
38,544,None,sunfloweroil.jpg,100.0,541,SUNFLOWER,None,None,0,0,0,100,1/2 Kg,Available
39,547,None,sunfloweroil.jpg,200.0,541,SUNFLOWER,None,None,0,0,0,200,1 Kg,Available
40,553,None,peanut_oil.jpg,220.0,550,PEANUT,None,None,0,0,0,220,1 Kg,Available
41,556,None,peanut_oil.jpg,110.0,550,PEANUT,None,None,0,0,0,110,1/2 Kg,Available
42,562,None,olive_oil.jpg,140.0,559,PEANUT,None,None,0,0,0,140,1/2 Kg,Available
43,565,None,olive_oil.jpg,280.0,559,PEANUT,None,None,0,0,0,280,1 Kg,Available
44,571,None,mango_juice.jpg,50.0,568,MANGOJUICE,None,None,0,0,0,50,500 ml,Available
45,574,None,mango_juice.jpg,100.0,568,MANGOJUICE,None,None,0,0,0,100,1 lt,Available
46,580,None,pineapple_juice.jpg,40.0,577,PINEAPPLEJUICE,None,None,0,0,0,40,500 ml,Available
47,583,None,pineapple_juice.jpg,20.0,577,PINEAPPLEJUICE,None,None,0,0,0,20,250 ml,Available
48,589,None,mosambi_juice.jpg,30.0,586,MOSAMBIJUICE,None,None,0,0,0,30,250 ml,Available
49,592,None,mosambi_juice.jpg,60.0,586,MOSAMBIJUICE,None,None,0,0,0,60,500 ml,Available
50,598,None,basmati_rice.jpg,130.0,595,BASMATIRICE,None,None,0,0,0,130,1 Kg,Available
51,601,None,basmati_rice.jpg,65.0,595,BASMATIRICE,None,None,0,0,0,65,1/2 Kg,Available
52,607,None,sonamasuri.jpg,60.0,604,SONAMASURIRICE,None,None,0,0,0,60,1/2 Kg,Available
53,610,None,sonamasuri.jpg,120.0,604,SONAMASURIRICE,None,None,0,0,0,120,1 Kg,Available
54,616,None,brown_rice.jpg,150.0,613,BROWNRICE,None,None,0,0,0,150,1 Kg,Available
55,619,None,brown_rice.jpg,75.0,613,BROWNRICE,None,None,0,0,0,75,1/2 Kg,Available

productDf

In [53]:
cursor1 = mydb.cursor()

queryproductDf = "SELECT * FROM ecomm.product"

cursor1.execute("SELECT * FROM ecomm.product")

product = cursor1.fetchall()

# productDf = pd.read_sql(queryproductDf, mydb)
productDf = pd.read_sql_query("SELECT * FROM ecomm.product", mydb)

productDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\502948950.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  productDf = pd.read_sql_query("SELECT * FROM ecomm.product", mydb)

,product_id,product_desc,product_name,search_tag,store_id,manufacturer_id
0,343,Toor Dal,Toor Dal,"Toor Dal, Kandipappu",1,1
1,361,Moong Dal,Moong Dal,"Moong Dal, Pesarapappu",1,2
2,370,Desi Ghee,Desi Ghee,Ghee,1,1
3,398,Channa Dal,Channa Dal,Channa Dal,1,1
4,406,Carrots,Carrots,Carrots,1,1
5,415,Potatoes,Potatoes,Potatoes,1,1
6,424,Cauliflower,Cauliflower,Cauliflower,1,2
7,433,Tomatoes,Tomatoes,Tomatoes,1,1
8,442,Green Beans,Green Beans,Green Beans,1,1
9,451,Mango Pickle,Mango Pickle,Mango Pickle,1,2
10,460,Lime Pickle,Lime Pickle,Lime Pickle,1,2
11,469,Mixed Vegetable Pickle,Mixed Vegetable Pickle,Mixed Vegetable Pickle,1,2
12,478,Ginger Pickle,Ginger Pickle,Ginger Pickle,1,2
13,487,Mixture,Mixture,Mixture,1,2
14,496,Sweets,Sweets,Sweets,1,2
15,505,Mangoes,Mangoes,Mangoes,1,3
16,514,Papaya,Papaya,Papaya,1,3
17,523,Sapota,Sapota,Sapota,1,3
18,532,Cheddar Cheese,Cheddar Cheese,Cheddar Cheese,1,4
19,541,Sunflower Oil,Sunflower Oil,Sunflower Oil,1,5
20,550,Peanut Oil,Peanut Oil,Peanut Oil,1,5
21,559,Olive Oil,Olive Oil,Olive Oil,1,5
22,568,Mango Juice,Mango Juice,Mango Juice,1,6
23,577,Pineapple Juice,Pineapple Juice,Pineapple Juice,1,6
24,586,MosambiJuice,MosambiJuice,MosambiJuice,1,6
25,595,Basmati Rice,Basmati Rice,Basmati Rice,1,7
26,604,Sona Masuri Rice,Sona Masuri Rice,Sona Masuri Rice,1,7
27,613,Brown Rice,Brown Rice,Brown Rice,1,7

productSkuRatingDf

In [50]:
cursor3 = mydb.cursor()

queryproductSkuRatingDf = "SELECT * FROM ecomm.product_sku_customer_ratings"

cursor3.execute(queryproductSkuRatingDf)

skuRating = cursor3.fetchall()

# productSkuRatingDf = pd.DataFrame(skuRating)
productSkuRatingDf = pd.read_sql(queryproductSkuRatingDf, mydb)

productSkuRatingDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\1858244438.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  productSkuRatingDf = pd.read_sql(queryproductSkuRatingDf, mydb)

,id,customer_id,feedback,last_update,product_sku_id,rating,recemended_flag,review_title_txt,recommended_flag,user_id
0,1,1,Good proudct,2019-08-22 16:11:11,5,4,yes,Good,None,None
1,2,2,It's good quality fabric.,2019-08-22 16:11:11,5,4,yes,Good,None,None
2,3,3,however I ordered the usual size but it dis no...,2019-08-22 16:29:10,6,5,yes,Excellent,None,None
3,4,4,I FEEL UNFIT,2019-08-22 18:17:10,6,2,No,Bad,None,None
4,5,5,Overall good.,2019-08-28 11:44:16,6,3,yes,avg,None,None
5,6,6,Very nice colour and material is also good.,2019-08-30 18:00:25,1,3,yes,Good,None,None
6,7,7,good quality and good fit,2019-08-30 18:27:50,1,3,yes,avg,None,None
7,8,8,The shirt is of excellent and durable quality....,2019-08-30 18:29:40,1,4,no,Excellent,None,None
8,9,9,It worth of money.It is made of pure cotton. D...,2019-08-30 18:31:06,1,4,yes,Nice,None,None
9,10,10,Dont go by the image....its totally different ...,2019-08-30 18:32:29,1,1,No,Bad,None,None
10,11,11,Dont go by the image....its totally different ...,2019-08-30 18:32:29,2,1,No,Bad,None,None
11,12,12,Nice product but it is not the same colour in ...,2019-08-30 18:32:29,2,3,No,Nice,None,None
12,13,13,It's.. Very excellent shirt.. And product qual...,2019-08-30 18:32:29,2,4,Yes,Excellent,None,None
13,14,14,really soft and colour is also as expected,2019-08-30 18:32:29,2,3,Yes,Avg,None,None
14,15,15,Very good quality. Really pure cotton. Size li...,2019-08-30 18:32:29,2,3,Yes,Good,None,None
15,16,16,Really very good quality of material. Fitting ...,2019-09-04 15:52:57,3,4,yes,Very Good,None,None
16,17,17,Very good quality. Really pure cotton. Size li...,2019-09-04 15:52:57,3,3,yes,Good,None,None
17,18,18,The pic shows wrong design,2019-09-04 15:52:57,3,2,No,Bad,None,None
18,19,19,Very happy to get this product within budget p...,2019-09-04 15:52:57,3,4,No,Nice,None,None
19,20,20,PERFECT FITTING AND FABULOUS FEBRIC QUALITY JU...,2019-09-04 15:52:57,3,4,yes,Excellent,None,None
20,21,21,Perfect fit product,2019-09-06 16:21:20,4,3,yes,Good,None,None
21,22,22,Customer Reviews,2019-09-10 11:56:37,3,2,No,Bad,None,None
22,51,23,Good quality products I like it.It's good qual...,2019-09-10 13:00:01,4,4,Yes,Nice,None,None
23,139,0,pRODUCT IS GOOD,2021-02-24 05:30:00,1,5,None,Best Product,Y,None
24,208,0,This product is wonderful go for it.,2021-03-25 05:30:00,1,5,None,best go for it,Y,None
25,209,0,Product is Not Bad,2021-03-25 05:30:00,1,5,None,Best Product,Y,None
26,210,0,This is very good producg,2021-03-25 05:30:00,1,0,None,very good product,Y,None
27,252,0,efonbenoibwinorbwrnoi,2021-04-08 05:30:00,24,5,None,fbnsobnieaiob,N,None
28,253,0,srnnmrnsfgnfgdn,2021-04-08 05:30:00,24,1,None,rgwrrbsbssb,Y,None
29,254,0,ryrmw5ymwrsmrsym,2021-04-08 05:30:00,24,1,None,h4thwrbngn,Y,None
30,259,0,advadvadsv,2021-04-09 05:30:00,3,5,None,avav,Y,None
31,265,0,f,2021-04-10 05:30:00,1,1,None,dfh,Y,None
32,266,0,asgdfgh,NaT,0,0,None,aesgdgfh,N,None

orderItemDf

In [49]:
cursor4 = mydb.cursor()

queryorderItemDf = "SELECT * FROM ecomm.order_item"

cursor4.execute(query)

orderItem = cursor4.fetchall()

# orderItemDf = pd.DataFrame(orderItem)
orderItemDf = pd.read_sql(queryorderItemDf, mydb)

orderItemDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\360529731.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderItemDf = pd.read_sql(queryorderItemDf, mydb)

,order_item_id,discount_applied,gift_wrapped,mrp_price,order_id,price,product_id,product_name,product_sku,quantity,pg_razor_pay_refund_id,status,total_price,discount_amt,final_price,order_order_id
0,204,0,yes,600,203,600.0,1,Mens Checkered Casual Spread Shirt,42,1,None,None,None,None,None,None
1,205,no,yes,700,203,700.0,8,Boy's Solid Cotton T Shirt,51,1,None,None,None,None,None,None
2,206,no,yes,3000.0,203,1500.0,2,Regular Women's Black Jeans,4,2,None,None,None,None,None,None
3,207,no,yes,750,203,750.0,7,Casual Full Sleeve Solid Women's Light Blue Top,14,1,None,None,None,None,None,None
4,209,0,yes,600,208,600.0,1,Mens Checkered Casual Spread Shirt,42,1,None,None,None,None,None,None
5,210,no,yes,890,208,890.0,4,Solid Men Round Neck White T-Shirt,47,1,None,None,None,None,None,None
6,211,no,yes,575,208,575.0,5,Men's Solid Straight Kurta,32,1,None,None,None,None,None,None
7,212,no,yes,700,208,700.0,8,Boy's Solid Cotton T Shirt,51,1,None,None,None,None,None,None
8,215,no,yes,1000,213,1000.0,3,Full Sleeve Solid Men's Sweatshirt,6,1,None,None,None,None,None,None
9,217,0,yes,1200.0,216,600.0,1,Mens Checkered Casual Spread Shirt,42,2,None,None,None,None,None,None
10,219,no,yes,1500.0,216,750.0,7,Casual Full Sleeve Solid Women's Light Blue Top,14,2,None,None,None,None,None,None
11,222,0,yes,2400,221,2400.0,4,Solid Men Round Neck White T-Shirt,8,1,None,None,None,None,None,None
12,224,0,yes,600,223,600.0,1,Mens Checkered Casual Spread Shirt,42,1,None,None,None,None,None,None
13,225,no,yes,899,223,899.0,6,Full Sleeve Solid Men Jacket,11,1,None,None,None,None,None,None
14,227,0,yes,900,226,900.0,1,Mens Checkered Casual Spread Shirt,2,1,None,None,None,None,None,None
15,228,no,yes,1500,226,1500.0,2,Regular Women's Black Jeans,4,1,None,None,None,None,None,None
16,230,0,yes,850,229,850.0,1,Mens Checkered Casual Spread Shirt,1,1,None,None,None,None,None,None
17,231,no,yes,1500,229,1500.0,2,Regular Women's Black Jeans,4,1,None,None,None,None,None,None
18,233,0,yes,1050,232,1050.0,3,Full Sleeve Solid Men's Sweatshirt,30,1,None,None,None,None,None,None
19,235,0,yes,890,234,890.0,4,Solid Men Round Neck White T-Shirt,47,1,None,None,None,None,None,None
20,237,0,yes,600,236,600.0,1,Mens Checkered Casual Spread Shirt,42,1,None,None,None,None,None,None
21,239,0,yes,600,238,600.0,1,Mens Checkered Casual Spread Shirt,42,1,None,None,None,None,None,None
22,241,0,yes,890,240,890.0,4,Solid Men Round Neck White T-Shirt,47,1,None,None,None,None,None,None
23,304,0,yes,570,303,570.0,5,Men's Solid Straight Kurta,9,1,None,None,None,None,None,None
24,628,no,yes,40,305,40.0,577,Pineapple Juice,580,1,None,None,None,None,None,None
25,629,no,yes,20,305,20.0,577,Pineapple Juice,583,1,None,None,None,None,None,None
26,635,0,yes,40.0,634,20.0,577,Pineapple Juice,583,2,None,None,None,None,None,None
27,636,no,yes,75,634,75.0,451,Mango Pickle,457,1,None,None,None,None,None,None
28,637,no,yes,80,634,80.0,523,Sapota,526,1,None,None,None,None,None,None
29,640,0,yes,75,649,75.0,451,Mango Pickle,457,1,None,None,None,None,None,None
30,784,0,yes,20.0,653,20.0,577,Pineapple Juice,583,1,None,None,None,None,None,None
31,785,no,yes,60,653,60.0,586,MosambiJuice,592,1,None,None,None,None,None,None
32,786,no,yes,80,653,80.0,523,Sapota,526,1,None,None,None,None,None,None
33,811,no,yes,150,676,150.0,451,Mango Pickle,454,1,None,None,None,None,None,None
34,812,no,yes,60,676,60.0,586,MosambiJuice,592,1,None,None,None,None,None,None
35,813,no,yes,30,676,30.0,586,MosambiJuice,589,1,None,None,None,None,None,None
36,821,no,yes,150.0,678,50.0,514,Papaya,520,3,None,None,None,None,None,None
37,839,no,yes,40.0,681,20.0,577,Pineapple Juice,583,2,None,None,None,None,None,None
38,840,no,yes,30,681,30.0,586,MosambiJuice,589,1,None,None,None,None,None,None
39,841,no,yes,60,681,60.0,586,MosambiJuice,592,1,None,None,None,None,None,None

orderStatusDf

In [48]:
cursor5 = mydb.cursor()

queryorderStatusDf = "SELECT * FROM ecomm.order_status"

cursor5.execute("SELECT * FROM ecomm.order_status")

orderStatus = cursor5.fetchall()

orderStatusDf = pd.read_sql(queryorderStatusDf, mydb)

orderStatusDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\587422765.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderStatusDf = pd.read_sql(queryorderStatusDf, mydb)

,order_track_ref,comment,date_sent,estimated_time,latitude,longitude,order_id,order_track_desc,order_track_update_time,person_identifier,status_cd,status_cd_id,razor_pay_order_id,razor_payment_id
0,1,None,None,2020-01-02 16:52:01,0.0,0.0,0,payment completed,2019-12-24 16:52:01,0,Out for delivery,3,None,None
1,2,None,None,2020-01-01 16:54:51,0.0,0.0,0,payment completed,2019-12-24 16:54:51,0,Ordered,0,None,None
2,3,None,None,2020-01-02 16:54:51,0.0,0.0,0,payment completed,2019-12-24 16:54:51,0,Out for delivery,3,None,None
3,4,None,None,2020-01-01 16:58:58,0.0,0.0,0,payment completed,2019-12-24 16:58:58,0,Ordered,0,order_HIUj3BKiLsdScj,pay_HIUk29rLwbwVT7
4,5,None,None,2020-01-03 16:59:10,0.0,0.0,0,payment completed,2019-12-24 16:59:10,0,Out for delivery,3,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,555,None,None,2022-10-08 10:15:57,0.0,0.0,653,payment completed,2022-09-30 10:15:57,0,Ordered,0,order_KNz6UBNJDf9NZP,pay_KNz6c4mkaQqBPE
555,556,None,None,NaT,0.0,0.0,678,None,NaT,0,None,0,order_KRxoKksbdoCURv,None
556,557,None,None,2022-10-18 11:36:06,0.0,0.0,678,payment completed,2022-10-10 11:36:06,0,Ordered,0,order_KRxoKksbdoCURv,pay_KRxoYiflNCh6Em
557,558,None,None,NaT,0.0,0.0,676,None,NaT,0,None,0,order_KRyO1PNFL2Om7V,None
558,559,None,None,2022-10-18 12:09:58,0.0,0.0,676,payment completed,2022-10-10 12:09:58,0,Ordered,0,order_KRyO1PNFL2Om7V,pay_KRyOKf3sCYn7mJ

ordersDf

In [47]:
cursor6 = mydb.cursor()

queryordersDf ="SELECT * FROM ecomm.orders"

cursor6.execute("SELECT * FROM ecomm.orders")

orders = cursor6 .fetchall()

ordersDf = pd.read_sql(queryordersDf, mydb)

ordersDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\1153254612.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ordersDf = pd.read_sql(queryordersDf, mydb)

,order_id,coupon_applied,customer_id,delivery_person_id,order_mod_dt_tm,pg_razorpay_order_id,pg_razorpay_payment_id,shipping_address_id,status,total_amount,user_id,order_submit_dt_tm
0,203,0,rohit,0,None,order_Ig1aBre1f2F9De,pay_Ig1b4CAh4e4cPm,1314,SUBMITTED,5050.0,219,2022-01-05 14:36:35
1,208,0,shanti putta,0,None,order_Ig2AR1TuNG3m7w,pay_Ig2ApwWEtfuOwM,1291,,2765.0,1264,2022-01-05 15:29:37
2,213,0,rohit,0,None,order_Ig1kBmgGEdeLBu,pay_Ig1kRfYiAfeXSH,1314,SUBMITTED,1000.0,219,2022-01-05 15:48:49
3,216,0,rohit,0,None,order_Ig1zXld9xi97Lx,None,1314,SUBMITTED,2700.0,219,2022-01-05 16:00:40
4,221,0,shanti putta,0,None,order_Ig2BjSxCi4eu2H,pay_Ig2C2GkJIPIa8Q,1291,,2400.0,1264,2022-01-05 16:22:21
5,223,0,rohit,0,None,order_Ig42brlLfe8sct,pay_Ig42vcQtCtQMaA,1314,SUBMITTED,1499.0,219,2022-01-05 18:10:54
6,226,0,Prem,0,None,order_Ig4AoEWXmHfb6j,pay_Ig4Bim25NNMEQT,224,SUBMITTED,2400.0,166,2022-01-05 18:17:10
7,229,0,Shanti,0,None,None,None,0,OPEN,2350.0,375,2022-01-05 18:52:47
8,232,0,Vs Vudupala,0,None,order_IgKjlGVj2GZYmm,pay_IgKk7dGrBwtNwF,1177,SUBMITTED,1050.0,1160,2022-01-06 10:31:02
9,234,0,Vs Vudupala,0,None,order_IgKkk419UZ41py,pay_IgKlEYzrPO0Lwg,1177,SUBMITTED,890.0,1160,2022-01-06 10:31:58
10,236,0,rohit,0,None,order_IhDjCJimthSbQn,pay_IhDjVEWdCgfmet,1314,SUBMITTED,600.0,219,2022-01-06 17:44:11
11,238,0,Prem,0,None,order_IhBs02FHhoVDM3,pay_IhBsjQMRiSXU96,222,SUBMITTED,600.0,166,2022-01-08 14:29:32
12,240,0,Prem,0,None,order_IhBuWgSj34QuW6,pay_IhBusie2wMytdr,223,SUBMITTED,890.0,166,2022-01-08 14:32:03
13,303,0,rohit,0,None,order_IqL7pCBZpy3r05,pay_IqL897FZloN0OX,1314,SUBMITTED,570.0,219,2022-01-31 17:16:23
14,305,1,rohit,0,None,order_Jw4vISzJNOWH9j,pay_Jw4vd11s7YMijp,1314,SUBMITTED,60.0,219,2022-01-31 17:31:06
15,634,1,rohit,0,None,order_Jwhj0UZ5eS6Ioz,pay_JwhjQMnIBl95CF,1314,SUBMITTED,195.0,219,2022-07-21 21:50:00
16,649,0,vamshi,0,None,order_KNmcO4g6NY6N99,pay_KNmcZXraP5mXfn,732,SUBMITTED,75.0,643,2022-09-29 22:02:33
17,653,0,vamshi,0,None,order_KNz6UBNJDf9NZP,pay_KNz6c4mkaQqBPE,732,SUBMITTED,160.0,643,2022-09-30 10:14:43
18,676,0,ramu,0,None,order_KRyO1PNFL2Om7V,pay_KRyOKf3sCYn7mJ,1446,SUBMITTED,240.0,795,2022-10-01 17:30:32
19,677,0,suman,0,None,None,None,0,OPEN,0.0,804,2022-10-01 20:06:54
20,678,0,ramu,0,None,order_KRxoKksbdoCURv,pay_KRxoYiflNCh6Em,1446,SUBMITTED,150.0,795,2022-10-02 08:15:01
21,680,0,Arun,0,None,None,None,0,OPEN,450.0,823,2022-10-08 17:51:21
22,681,0,ramu,0,None,None,None,0,OPEN,130.0,795,2022-10-11 12:40:58

In [46]:
cursor7 = mydb.cursor()

queryorderStatusRef = "SELECT * FROM ecomm.order_status_ref"

cursor7.execute("SELECT * FROM ecomm.order_status_ref")

orderStatusRef = cursor7.fetchall()

orderStatusRefDf = pd.read_sql(queryorderStatusRef, mydb)

orderStatusRefDf

C:\Users\ADMIN_2\AppData\Local\Temp\ipykernel_15556\1340150132.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderStatusRefDf = pd.read_sql(queryorderStatusRef, mydb)

   status_id         status_code
0          0                PAID
1          1             Shipped
2          2          In transit
3          3    Out for delivery
4          4  delivery completed